### ISSUE TITLE
Python implementation returning error 

### ISSUE THREAD

**Issue by annashcherbina** [REFRAME/prg#2]
Hello, I am getting auPRG = 0.9743 with the R implementation of the algorithm in the attached test case.  

labels.csv holds the "true labels" and pred_prbs.csv returns the predicted values. However, the Python implementation gives the following warning: 

```
 RuntimeWarning: invalid value encountered in add
 new_point = point_2 + alpha*delta
```

The auPRG is also -0.487 in the Python output. 

Do you have any idea what would cause this discrepancy? 
One thing that I have considered is that "pred_prbs.csv" contains the output predicted classes (rather than the output predicted probabilities) -- will the code handle this case correctly? 

Also, would we ever observe a case when the auPRG value is higher than the auPRC? The other metrics for the test case are: 

```
Bal Acc: 0.813  auROC: 0.813    auPRC: 0.388    auPRG: -0.487   F1: 0.220       Re@0.50 FDR: 0.000      Re@0.25 FDR: 0.000      Re@0.10 FDR: 0.000      Re@0.05 FDR: 0.000      Positive Accuracy: 0.643 (6461/10051)   Negative Accuracy: 0.984 (2627948/2670236)
```

It seems a bit odd that the auPRG value (from R) is so high? 

Thank you so much, any help would be greatly appreciated! 
[test_case.zip](https://github.com/REFRAME/prg/files/371870/test_case.zip)

**Comment by meeliskull** [comment]
Thanks for reporting this issue! There was a bug in the Python code, it is now fixed. Please run 'pip install --upgrade pyprg'. The value auPRG=0.9743 from R is correct, now Python code gives the same value. Also note that I have removed the parameter 'create_crossing_points = True' from create_prg_curve, now it is always true, and the crossing points are always created.
